### ISSUE TITLE
Please add support for H70C4

### ISSUE THREAD

**Issue by fr00sch** [Galorhallen/govee-local-api#62]
It would be nice, if this device is also added. Tank you

**Comment by Galorhallen** [comment]
Hi, this is the christmas light, correct? Does it support white temperature in addition to RGB colors?

**Comment by ramundomario** [comment]
Hey @Galorhallen 👋 
Yep, exactly. The product is the ["Christmas String Lights 2"](https://eu.govee.com/products/christmas-string-lights-2?variant=48557635305656) that should be an upgrade of the ["Christmas String Lights"](https://eu.govee.com/products/govee-christmas-string-lights?srsltid=AfmBOop7ZiNYxo0iY8XGDg7DlrhqqZaOXsiZgLYd6UeIzL3c1H_JLz_L) ([`H70C1`/`H70C2`](https://github.com/Galorhallen/govee-local-api/blob/d95a6965329ff939b66e6db7a2c2dd722676d02f/src/govee_local_api/light_capabilities.py#L375-L384)) already supported by this project.
The same product is available in `H70C5` variant that differs only on the length of the strips.

I'll have the variant `H70C5` in a few days (in order to tests it), but I'd guess that they support the white temperature as the old model.

Thanks a lot for the package 💪

**Comment by ramundomario** [comment]
Someone owning the `H70C4` could help with [this point](https://github.com/Galorhallen/govee-local-api/pull/80#discussion_r1871907657)? Thanks

**Comment by mitchkeller** [comment]
H70C7 should also be supported. This is another length of the same type of string lights. I’ve checked and I can control 10 segments in the app as well, like the others.

**Comment by lubbertkramer** [comment]
Is it correct this now only supports on/off instead of more functionality? 

I have the following error
Device H70C4 is not supported. Only power control is available. Please open an issue at 'https://github.com/Galorhallen/govee-local-api/issues'

**Comment by ramundomario** [comment]
> Is it correct this now only supports on/off instead of more functionality?
> 
> I have the following error Device H70C4 is not supported. Only power control is available. Please open an issue at 'https://github.com/Galorhallen/govee-local-api/issues'

The support has been added in https://github.com/Galorhallen/govee-local-api/pull/80 but not yet released into HomeAssistant
See https://github.com/Galorhallen/govee-local-api/issues/82
